FROM ubuntu:16.04
MAINTAINER Michael Lucas <michael.lucas@tempus.com>

# Install all packages for container
RUN apt-get update && apt-get install -y \
      apt-transport-https \
      curl \
      git \
      libcurl4-openssl-dev \
      libssl-dev \
      lsb-release \
      python3-dev \
      python3-pip

# Create celery directory
RUN mkdir /opt/celery

# Set up Google Cloud Vision credentials
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk

COPY /google_creds.json /opt/celery
ENV GOOGLE_APPLICATION_CREDENTIALS /opt/celery/google_creds.json

# Install python dependencies
COPY /requirements.txt /opt/celery/
WORKDIR /opt/celery
RUN pip3 install -r requirements.txt

# Add code and credentials to container
COPY /celery_project /opt/celery/code

# Install Python requirements
WORKDIR /opt/celery/code

# Run Python service
CMD ["python3", "worker.py","worker"]
